import paneerSalad from "@/assets/paneer-moong-salad.jpg";
import nutriaiMark from "@/assets/nutriai-mark.png";
import { Conversation, ConversationContent, ConversationEmptyState, ConversationScrollButton } from "@/components/ai-elements/conversation";
import { Message, MessageContent, MessageResponse } from "@/components/ai-elements/message";
import { PromptInput, PromptInputFooter, PromptInputSubmit, PromptInputTextarea } from "@/components/ai-elements/prompt-input";
import { Shimmer } from "@/components/ai-elements/shimmer";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { loadChat } from "@/lib/chat.functions";
import { useChat } from "@ai-sdk/react";
import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { DefaultChatTransport, type UIMessage } from "ai";
import { Activity, BarChart3, BookOpen, ChefHat, CircleUserRound, HeartPulse, Home, MessageCircle, Plus, Search, UtensilsCrossed } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis } from "recharts";
import { toast } from "sonner";

export const Route = createFileRoute("/_authenticated/dashboard")({ component: Dashboard });
const chartData = [{ day: "Mon", kcal: 1810 }, { day: "Tue", kcal: 2050 }, { day: "Wed", kcal: 1930 }, { day: "Thu", kcal: 1840 }, { day: "Fri", kcal: 2140 }, { day: "Sat", kcal: 1980 }, { day: "Sun", kcal: 1760 }];

function Dashboard() {
  const { user } = Route.useRouteContext(); const navigate = useNavigate();
  const [initial, setInitial] = useState<UIMessage[]>([]); const [ready, setReady] = useState(false); const inputRef = useRef<HTMLTextAreaElement>(null);
  useEffect(() => { loadChat().then(setInitial).catch(() => setInitial([])).finally(() => setReady(true)); }, []);
  const tokenTransport = useMemo(() => new DefaultChatTransport({ api: "/api/chat", headers: async () => { const { data } = await supabase.auth.getSession(); return data.session?.access_token ? { Authorization: `Bearer ${data.session.access_token}` } : {}; } }), []);
  if (!ready) return <div className="flex min-h-screen items-center justify-center"><Shimmer>Preparing your nutrition desk…</Shimmer></div>;
  return <DashboardContent key="single-chat" initial={initial} transport={tokenTransport} userEmail={user.email ?? ""} onSignOut={async () => { await supabase.auth.signOut(); navigate({ to: "/auth", replace: true }); }} inputRef={inputRef} />;
}

function DashboardContent({ initial, transport, userEmail, onSignOut, inputRef }: { initial: UIMessage[]; transport: DefaultChatTransport<UIMessage>; userEmail: string; onSignOut: () => Promise<void>; inputRef: React.RefObject<HTMLTextAreaElement | null> }) {
  const { messages, sendMessage, status, stop } = useChat({ id: "nutrition-assistant", messages: initial, transport, onError: (error) => toast.error(error.message) });
  useEffect(() => { inputRef.current?.focus(); }, [status, inputRef]);
  const firstName = userEmail.split("@")[0] || "friend";
  const nav = [{ label: "Today", icon: Home }, { label: "Recipes", icon: ChefHat }, { label: "Meal tracker", icon: UtensilsCrossed }, { label: "Analytics", icon: BarChart3 }, { label: "Saved", icon: BookOpen }];
  return <div className="min-h-screen lg:grid lg:grid-cols-[248px_1fr]">
    <aside className="hidden border-r border-primary/10 bg-primary px-5 py-7 text-primary-foreground lg:flex lg:flex-col"><div className="flex items-center gap-3 px-2"><img src={nutriaiMark} alt="NutriAI" className="size-11 rounded-xl bg-card"/><span className="font-serif text-2xl">NutriAI</span></div><nav className="mt-12 space-y-2">{nav.map(({ label, icon: Icon }, index) => <Button key={label} variant="ghost" className={`w-full justify-start rounded-xl ${index === 0 ? "bg-primary-foreground/12 text-primary-foreground" : "text-primary-foreground/65 hover:bg-primary-foreground/8 hover:text-primary-foreground"}`}><Icon/>{label}</Button>)}</nav><div className="mt-auto rounded-2xl bg-primary-foreground/8 p-4"><p className="text-xs uppercase tracking-widest text-accent">Profile health</p><div className="mt-3 h-1.5 rounded-full bg-primary-foreground/10"><div className="h-full w-4/5 rounded-full bg-accent"/></div><p className="mt-2 text-xs text-primary-foreground/65">80% complete</p></div></aside>
    <main className="min-w-0"><header className="sticky top-0 z-30 flex h-20 items-center justify-between border-b border-primary/8 bg-background/85 px-5 backdrop-blur-xl md:px-9"><div className="flex items-center gap-3 lg:hidden"><img src={nutriaiMark} alt="NutriAI" className="size-9 rounded-lg"/><span className="font-serif text-xl text-primary">NutriAI</span></div><div className="hidden items-center gap-2 rounded-full border border-border bg-card px-4 py-2.5 text-sm text-muted-foreground md:flex"><Search className="size-4"/>Search recipes, meals, insights</div><div className="ml-auto flex items-center gap-3"><span className="hidden text-sm text-muted-foreground sm:block">{userEmail}</span><Button variant="outline" size="icon" className="rounded-full" onClick={onSignOut}><CircleUserRound/></Button></div></header>
      <div className="mx-auto max-w-[1500px] p-5 md:p-9"><section className="reveal flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-accent">Your daily nourishment</p><h1 className="mt-2 font-serif text-4xl md:text-5xl">Namaste, <em>{firstName}.</em></h1><p className="mt-3 max-w-2xl text-muted-foreground">Your plan is tuned for steady energy and high protein. You’re 38g away from today’s target.</p></div><Button variant="saffron" size="lg" className="rounded-full"><Plus/>Log a meal</Button></section>
        <div className="mt-8 grid gap-6 xl:grid-cols-[minmax(0,1.55fr)_minmax(340px,.75fr)]"><div className="space-y-6">
          <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[{ t: "Calories", v: "1,840", s: "/ 2,400", p: "77%", c: "bg-primary" }, { t: "Protein", v: "112g", s: "/ 150g", p: "75%", c: "bg-accent" }, { t: "Fiber", v: "23g", s: "/ 30g", p: "77%", c: "bg-chart-2" }, { t: "Hydration", v: "2.4L", s: "/ 3.2L", p: "75%", c: "bg-chart-3" }].map((x) => <div key={x.t} className="premium-card rounded-2xl p-5"><p className="text-[11px] font-bold uppercase tracking-[.18em] text-muted-foreground">{x.t}</p><p className="mt-3 text-2xl font-bold">{x.v} <span className="text-xs font-medium text-muted-foreground">{x.s}</span></p><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-muted"><div className={`h-full rounded-full ${x.c}`} style={{ width: x.p }}/></div></div>)}</section>
          <section className="relative min-h-[410px] overflow-hidden rounded-[2rem] bg-primary text-primary-foreground shadow-2xl shadow-primary/20"><div className="relative z-10 max-w-[58%] p-7 md:p-10"><span className="rounded-full bg-primary-foreground/10 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.2em] text-accent">AI recommended</span><h2 className="mt-5 font-serif text-3xl leading-tight md:text-4xl">High-Protein Paneer & Sprouted Moong Salad</h2><p className="mt-4 text-sm text-primary-foreground/66">Bright, affordable and balanced for your protein and iron goals.</p><div className="mt-7 flex flex-wrap gap-6 text-sm"><span><b>15m</b><small className="block text-primary-foreground/50">Prep</small></span><span><b>32g</b><small className="block text-primary-foreground/50">Protein</small></span><span><b>12g</b><small className="block text-primary-foreground/50">Fiber</small></span></div><Button variant="saffron" className="mt-8 rounded-full">View full recipe</Button></div><img src={paneerSalad} alt="High-protein paneer and sprouted moong salad" width={800} height={1024} className="absolute inset-y-0 right-0 h-full w-[47%] object-cover [mask-image:linear-gradient(to_right,transparent,black_35%)]"/></section>
          <section className="grid gap-6 md:grid-cols-[1.25fr_.75fr]"><div className="premium-card rounded-3xl p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Weekly energy</p><h3 className="mt-1 font-serif text-2xl">Balanced rhythm</h3></div><Activity className="text-primary"/></div><div className="mt-4 h-44"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="nutrition" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--color-primary)" stopOpacity=".35"/><stop offset="1" stopColor="var(--color-primary)" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="day" axisLine={false} tickLine={false} fontSize={11}/><Tooltip/><Area type="monotone" dataKey="kcal" stroke="var(--color-primary)" strokeWidth={3} fill="url(#nutrition)"/></AreaChart></ResponsiveContainer></div></div><div className="rounded-3xl bg-accent/14 p-6 ring-1 ring-accent/25"><HeartPulse className="text-accent-foreground"/><p className="mt-5 text-xs font-bold uppercase tracking-widest text-accent-foreground/60">Today’s nutrition gap</p><h3 className="mt-2 font-serif text-2xl">Protein short by 38g</h3><p className="mt-3 text-sm text-muted-foreground">Add masoor dal soup with two boiled eggs, or tofu if vegetarian.</p></div></section>
        </div><aside className="premium-card flex min-h-[640px] flex-col overflow-hidden rounded-3xl"><div className="flex items-center gap-3 border-b border-border p-5"><img src={nutriaiMark} alt="NutriAI assistant" className="size-10 rounded-xl"/><div><h2 className="font-serif text-xl">Nutrition concierge</h2><p className="text-xs text-muted-foreground">Profile-aware • always available</p></div><span className="ml-auto size-2.5 rounded-full bg-chart-2"/></div><Conversation className="min-h-0"><ConversationContent className="gap-5 p-5">{messages.length === 0 && <ConversationEmptyState icon={<MessageCircle className="size-8 text-primary"/>} title="Ask NutriAI" description="Try: How can I increase protein in dal bhat?"/>}{messages.map((message) => <Message key={message.id} from={message.role}><MessageContent className={message.role === "user" ? "bg-primary text-primary-foreground" : ""}>{message.parts.map((part, i) => part.type === "text" ? <MessageResponse key={i}>{part.text}</MessageResponse> : null)}</MessageContent></Message>)}{status === "submitted" && <Shimmer className="text-muted-foreground">Thinking with your health profile…</Shimmer>}</ConversationContent><ConversationScrollButton/></Conversation><div className="border-t border-border bg-card/60 p-4"><PromptInput onSubmit={async ({ text }) => { if (!text.trim()) return; await sendMessage({ text }); inputRef.current?.focus(); }}><PromptInputTextarea ref={inputRef} placeholder="Ask about swaps, macros, cooking…" className="min-h-20"/><PromptInputFooter className="justify-end"><PromptInputSubmit status={status} onStop={stop}/></PromptInputFooter></PromptInput><p className="mt-2 text-center text-[10px] text-muted-foreground">Guidance only — consult a clinician for medical decisions.</p></div></aside></div>
      </div><nav className="fixed inset-x-4 bottom-4 z-40 flex justify-around rounded-2xl bg-primary p-2 text-primary-foreground shadow-2xl lg:hidden">{nav.slice(0,4).map(({ label, icon: Icon }) => <Button key={label} variant="ghost" size="icon" className="rounded-xl text-primary-foreground"><Icon/><span className="sr-only">{label}</span></Button>)}</nav></main>
  </div>;
}