import nutriaiMark from "@/assets/nutriai-mark.png";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { supabase } from "@/integrations/supabase/client";
import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, Check } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export const Route = createFileRoute("/_authenticated/onboarding")({ component: Onboarding });
const goals = ["Weight Loss", "Fat Loss", "Muscle Gain", "Weight Gain", "Maintenance", "Healthy Eating", "Diabetes Management", "Heart Health", "Gut Health", "High Protein", "Low Carb", "Improve Energy", "Improve Immunity"];
const cuisines = ["Indian", "Nepali", "South Indian", "North Indian", "Chinese", "Thai", "Italian", "Continental", "Mediterranean"];
const allergies = ["Dairy", "Peanuts", "Tree Nuts", "Soy", "Wheat", "Seafood", "Eggs"];
const conditions = ["Diabetes", "High Blood Pressure", "Thyroid", "Cholesterol", "PCOS", "Gastric Issues", "IBS"];
const deficiencies = ["Iron Deficiency", "Vitamin D Deficiency", "Vitamin B12 Deficiency", "Calcium Deficiency", "Protein Deficiency"];

function Onboarding() {
  const { user } = Route.useRouteContext(); const navigate = useNavigate(); const [step, setStep] = useState(0);
  const [form, setForm] = useState({ full_name: "", age: "", gender: "", height_cm: "", weight_kg: "", country: "Nepal", city: "", health_goals: [] as string[], activity_level: "Moderately Active", dietary_type: "Vegetarian", cuisine_preferences: [] as string[], food_preferences: [] as string[], allergies: [] as string[], health_conditions: [] as string[], deficiencies: [] as string[] });
  const toggle = (key: "health_goals" | "cuisine_preferences" | "food_preferences" | "allergies" | "health_conditions" | "deficiencies", value: string) => setForm((f) => ({ ...f, [key]: f[key].includes(value) ? f[key].filter((x) => x !== value) : [...f[key], value] }));
  const choice = (key: Parameters<typeof toggle>[0], items: string[]) => <div className="flex flex-wrap gap-2">{items.map((item) => <button type="button" key={item} onClick={() => toggle(key, item)} className={`rounded-full border px-4 py-2.5 text-sm transition ${form[key].includes(item) ? "border-primary bg-primary text-primary-foreground" : "border-border bg-card hover:border-primary/40"}`}>{form[key].includes(item) && <Check className="mr-1 inline size-3"/>}{item}</button>)}</div>;
  async function finish() { const { error } = await supabase.from("profiles").upsert({ id: user.id, ...form, age: Number(form.age) || null, height_cm: Number(form.height_cm) || null, weight_kg: Number(form.weight_kg) || null, onboarding_completed: true }); if (error) toast.error(error.message); else navigate({ to: "/dashboard" }); }
  return <main className="min-h-screen p-5 md:p-10"><div className="mx-auto max-w-5xl"><header className="flex items-center justify-between"><div className="flex items-center gap-3"><img src={nutriaiMark} alt="NutriAI" className="size-11 rounded-xl"/><span className="font-serif text-2xl text-primary">NutriAI</span></div><span className="text-sm text-muted-foreground">Step {step + 1} of 4</span></header><div className="mt-8 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full bg-accent transition-all" style={{ width: `${(step + 1) * 25}%` }}/></div>
    <section className="premium-card mt-8 rounded-[2rem] p-6 md:p-10"><p className="text-xs font-bold uppercase tracking-[.25em] text-accent">Build your nutrition blueprint</p><h1 className="mt-3 font-serif text-4xl">{["Tell us about you", "What are you working toward?", "Your kitchen, your preferences", "Health guardrails"][step]}</h1><p className="mt-3 mb-8 text-muted-foreground">We use this only to personalize recipes, targets, and daily guidance.</p>
      {step === 0 && <div className="grid gap-4 md:grid-cols-2">{(["full_name", "age", "height_cm", "weight_kg", "city"] as const).map((key) => <Input key={key} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} placeholder={key.replaceAll("_", " ")} className="h-12 capitalize"/>)}<select className="h-12 rounded-md border border-input bg-card px-3" value={form.country} onChange={(e) => setForm({ ...form, country: e.target.value })}><option>Nepal</option><option>India</option></select><select className="h-12 rounded-md border border-input bg-card px-3" value={form.gender} onChange={(e) => setForm({ ...form, gender: e.target.value })}><option value="">Gender</option><option>Female</option><option>Male</option><option>Non-binary</option><option>Prefer not to say</option></select></div>}
      {step === 1 && <div className="space-y-7"><div><h2 className="mb-3 font-semibold">Health goals</h2>{choice("health_goals", goals)}</div><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Activity level<select className="mt-2 h-12 w-full rounded-md border border-input bg-card px-3" value={form.activity_level} onChange={(e) => setForm({ ...form, activity_level: e.target.value })}>{["Sedentary", "Lightly Active", "Moderately Active", "Very Active"].map(x => <option key={x}>{x}</option>)}</select></label><label className="text-sm font-medium">Dietary type<select className="mt-2 h-12 w-full rounded-md border border-input bg-card px-3" value={form.dietary_type} onChange={(e) => setForm({ ...form, dietary_type: e.target.value })}>{["Vegetarian", "Vegan", "Eggetarian", "Non-Vegetarian", "Jain", "Pescatarian"].map(x => <option key={x}>{x}</option>)}</select></label></div></div>}
      {step === 2 && <div className="space-y-7"><div><h2 className="mb-3 font-semibold">Cuisine preferences</h2>{choice("cuisine_preferences", cuisines)}</div><div><h2 className="mb-3 font-semibold">Food preferences</h2>{choice("food_preferences", ["Spicy", "Mild", "Sweet", "Savory"])}</div></div>}
      {step === 3 && <div className="space-y-7"><div><h2 className="mb-3 font-semibold">Allergies</h2>{choice("allergies", allergies)}</div><div><h2 className="mb-3 font-semibold">Health conditions</h2>{choice("health_conditions", conditions)}</div><div><h2 className="mb-3 font-semibold">Nutritional deficiencies</h2>{choice("deficiencies", deficiencies)}</div></div>}
      <footer className="mt-10 flex justify-between"><Button variant="ghost" disabled={step === 0} onClick={() => setStep(step - 1)}><ArrowLeft/>Back</Button><Button variant={step === 3 ? "saffron" : "premium"} onClick={() => step === 3 ? finish() : setStep(step + 1)}>{step === 3 ? "Create my plan" : "Continue"}<ArrowRight/></Button></footer>
    </section></div></main>;
}